#!/bin/bash
if [ $1='32' ]; then
	echo "ATmega 32"
	avr-gcc -w -mmcu=atmega32 -c Interrupt.c
	echo "Compiled"
	avr-gcc -w -mmcu=atmega32 Interrupt.o -o Interrupt
	echo "Built executable"
	avr-objcopy -O ihex Interrupt Interrupt.hex
	echo "Built hex"
	sudo avrdude -c usbasp -p m32 -U flash:w:Interrupt.hex
else	
	echo "ATmega 16"
	avr-gcc -w -mmcu=atmega16 -c Interrupt.c
	echo "Compiled"
	avr-gcc -w -mmcu=atmega16 Interrupt.o -o Interrupt
	echo "Built executable"
	avr-objcopy -O ihex Interrupt Interrupt.hex
	echo "Built hex"
	sudo avrdude -c usbasp -p m16 -U flash:w:Interrupt.hex
fi

