#!/bin/bash
if [ $1  = "32" ]; then
	echo "ATmega 32"
	avr-gcc -w -mmcu=atmega32 -c lcd2.c
	echo "Compiled"
	avr-gcc -w -mmcu=atmega32 lcd2.o -o lcd2
	echo "Built executable"
	avr-objcopy -O ihex lcd2 lcd2.hex
	echo "Built hex"
	sudo avrdude -c usbasp -p m32 -U flash:w:lcd2.hex
else	
	echo "ATmega 16"
	avr-gcc -w -mmcu=atmega16 -c lcd2.c
	echo "Compiled"
	avr-gcc -w -mmcu=atmega16 lcd2.o -o lcd2
	echo "Built executable"
	avr-objcopy -O ihex lcd2 lcd2.hex
	echo "Built hex"
	sudo avrdude -c usbasp -p m16 -U flash:w:lcd2.hex
fi

